parameters:
    php_to_js.class: Laracasts\Utilities\JavaScript\PHPToJavaScriptTransformer
    hospect.caching_view_binder.class: Hospect\PhpVarsToJsBundle\ViewBinder\CachingViewBinder
    hospect.js_extension.class: Hospect\PhpVarsToJsBundle\Twig\JavaScriptExtension

services:
    php_to_js:
        class: %php_to_js.class%
        arguments:
            - @hospect.caching_view_binder
            - %hospect_php_to_js.namespace%

    hospect.caching_view_binder:
        class: %hospect.caching_view_binder.class%
        public: false

    hospect.js_extension:
        class: %hospect.js_extension.class%
        tags:
            - { name: twig.extension }
